- repo: itchyny/lightline.vim
- repo: mattn/emmet-vim
- repo: tpope/vim-eunuch
- repo: tpope/vim-surround
- repo: sebastianmarkow/deoplete-rust
- repo: w0rp/ale
- repo: zchee/deoplete-clang
- repo: kien/rainbow_parentheses.vim
